// model.generate — agent tool. Text or an image becomes a mesh in the graph.
//
// The claim phase A4 makes is that a generated mesh takes the identical code path
// an imported GLB takes, and this file is where that claim is either kept or
// quietly broken. It keeps it by having nothing of its own: the handler ingests
// the bytes with `ingestSingleFile` and builds ops with
// `buildGltfImportOpsFromOpfs` — the same two functions the human drop path and
// `library.import` call, unmodified. There is no second road to keep in step and
// no provenance flag for anything downstream to branch on.
//
// Shaped after `library.import`, which is the closest sibling: async, brings an
// asset into the scene, returns Op[] for the Diff and NEVER dispatches (V7). It
// is a tool rather than a mutator for the reason A1 recorded: a mutator's `build`
// is synchronous and pure by contract, and generation is network I/O — modelling
// it as a mutator would mean either lying about purity or inventing a node type
// whose evaluation performs I/O, which is the provenance branch A4 exists to
// avoid.
//
// 🔴 ONE HONEST DIFFERENCE FROM library.import, STATED BECAUSE IT IS A SIDE
// EFFECT BEFORE ACCEPTANCE. `library.import` names an asset that already exists;
// generation has to create one, so this handler WRITES A FILE TO OPFS before it
// returns, and that write survives even if the director rejects the Diff. That is
// deliberate rather than overlooked: the ops reference the asset by path, so the
// bytes must exist for the ops to mean anything, and the generation has already
// been paid for by the time they arrive. A rejected Diff leaves a usable asset in
// My Imports rather than silently discarding something the director was billed
// for. What it must NOT do is dispatch, and it does not.
//
// The model version is NOT an argument. It is configuration: a director chooses
// it once in Settings, and the tool generates with what is configured. Letting
// the agent name a version per call would spread the surface across every prompt
// for no gain — the model is not choosing between capabilities, it is asking for
// a mesh.
//
// REF: src/agent/tools/libraryImport.ts (the pattern);
//      src/agent/tools/motionGenerate.ts (the A1 sibling);
//      src/app/asset/generateModel.ts (the human half);
//      ref/architecture/ai-track.md phase A4.

import { z } from 'zod';
import type { ToolContext, ToolDefinition, ToolResult } from './types';
import { MAX_FACE_LIMIT, describeRequest } from '../../core/modelgen';
import type { ModelGenerationRequest } from '../../core/modelgen';
import { ingestSingleFile } from '../../app/asset/importCommon';
import { buildGltfImportOpsFromOpfs } from '../../app/asset/importGltf';

export const modelGenerateSchema = z.object({
  prompt: z
    .string()
    .min(1, 'prompt is required — describe the object, e.g. "a worn leather armchair"')
    .describe('Natural-language description of the object to generate'),
  negativePrompt: z.string().optional().describe('What to avoid in the result'),
  faceLimit: z
    .number()
    .int()
    .positive()
    .max(MAX_FACE_LIMIT)
    .optional()
    .describe('Cap on output triangles; omitted lets the service decide'),
  quad: z
    .boolean()
    .optional()
    .describe('Ask for quads rather than triangles (default: the service decides)'),
  texture: z.boolean().optional().describe('Generate texture (default true)'),
  pbr: z.boolean().optional().describe('Generate PBR materials (default true)'),
  name: z.string().optional().describe('Name for the imported asset (defaults to the prompt)'),
});

export type ModelGenerateArgs = z.infer<typeof modelGenerateSchema>;

export const modelGenerateTool: ToolDefinition<ModelGenerateArgs> = {
  name: 'model.generate',
  description:
    'Generate a 3D mesh from a text description. Returns an Op[] that adds the ' +
    'identical nodes a dropped .glb file produces — GltfAsset, GltfChild and a ' +
    'Group wired to the scene — because the generated bytes are ingested and ' +
    'imported by the same two functions a file drop uses, so every road open to ' +
    'an imported mesh is open to this one. The model version and API key are ' +
    'configured in Settings, not chosen per call.',
  paramSchema: modelGenerateSchema,
  async handler(args: ModelGenerateArgs, ctx: ToolContext): Promise<ToolResult> {
    if (!ctx.modelCapability) {
      return {
        ops: [],
        text:
          'Error: no model-generation capability configured. Set a Tripo API key ' +
          'in Settings; with none configured the offline stub generates instead.',
      };
    }

    const sceneRef = ctx.dagState.outputs.scene;
    if (!sceneRef) {
      // Distinct from the case above on purpose: a project with no scene output
      // is a different problem from an unconfigured service, and reporting both
      // as one would send the reader to the wrong place.
      return { ops: [], text: 'Error: the project has no scene output to import into.' };
    }

    const request: ModelGenerationRequest = {
      source: 'text',
      prompt: args.prompt,
      ...(args.negativePrompt !== undefined ? { negativePrompt: args.negativePrompt } : {}),
      ...(args.faceLimit !== undefined ? { faceLimit: args.faceLimit } : {}),
      ...(args.quad !== undefined ? { quad: args.quad } : {}),
      ...(args.texture !== undefined ? { texture: args.texture } : {}),
      ...(args.pbr !== undefined ? { pbr: args.pbr } : {}),
      ...(ctx.modelVersion !== undefined ? { modelVersion: ctx.modelVersion } : {}),
    };

    let opfsPath: string;
    let taskId: string;
    try {
      const generated = await ctx.modelCapability.generate(request);
      taskId = generated.taskId;
      opfsPath = await ingestSingleFile(
        { relativePath: 'model.glb', bytes: new Uint8Array(generated.glb) },
        args.name ?? describeRequest(request),
      );
    } catch (err) {
      // A licence refusal, a rejected key and a transport failure all land here,
      // and all are things the model can act on — an unrecorded service is a
      // settings-and-paperwork problem, a timeout is a retry. Returning the
      // message beats throwing, which would end the turn with nothing to read.
      return {
        ops: [],
        text: `Error: model generation failed — ${err instanceof Error ? err.message : String(err)}`,
      };
    }

    // V7 — the FORKED state, never the live store. The tool returns ops for the
    // Diff; the director accepts before anything in the graph changes.
    const chain = await buildGltfImportOpsFromOpfs(opfsPath, sceneRef.node, ctx.dagState);

    return {
      ops: chain.ops,
      text:
        `Generated "${args.name ?? args.prompt}" (task ${taskId}) — imported as ` +
        `${opfsPath}, GltfAsset ${chain.gltfAssetId}. It is an ordinary imported ` +
        `asset, with nothing in the graph marking it as generated.`,
    };
  },
};
