// glTF spec/gloss .glb direct-import (#216, V53) — the binary-container twin of
// gltf-specgloss-capture.spec.ts (#214, which covers the .gltf folder).
//
// A spec/gloss .glb used to import flat-gray: ingestGltfFolder gated the
// KHR_materials_pbrSpecularGlossiness → metal-rough conversion on the .gltf
// extension because Basher had no GLB writer. #216 adds repackGlb + convertSpecGlossGlb,
// so a .glb now converts AT INGEST exactly like a .gltf — one point before everything
// that reads the file, so render == capture.
//
// THE BOUNDARY-PAIR PROOF (falsifiable). The fixture (public/assets/specgloss-quad.glb,
// generated by scripts/gen-specgloss-glb-fixture.mjs) has TWO spec/gloss materials
// and stores its combined specularGlossinessTexture as a bufferView image INSIDE
// the embedded BIN chunk (the realistic GLB case the .gltf path's sibling resolver
// can't reach):
//   side A (the DAG) — each mesh's captured material is normal metal-rough, and the
//     combined material's roughness and metalness maps are ONE baked image.
//   side B (the draw) — the drawn three.js material carries the base map and, for the
//     combined material, a metalnessMap/roughnessMap.
// Pre-#216 both materials would be default-white with null maps.
//
// #1071 — the file arrives as native geometry (#1050): every image, the baked ones
// included, is stored in the project and named by content hash.

import { test, expect } from './_fixtures';
import { drawnImportMeshes, importedMeshes } from './_importedMesh';

interface CapturedMap {
  hash: string;
  colorSpace: string;
  flipY: boolean;
  store?: string;
}
interface CapturedMaterial {
  name: string;
  base: { color: string; metalness: number };
  specular: { roughness: number };
  maps: {
    albedo: CapturedMap | null;
    roughness: CapturedMap | null;
    metalness: CapturedMap | null;
  };
}
interface BasherWindow {
  __basher_ingestGltfFolder: (
    files: { relativePath: string; bytes: Uint8Array }[],
    folderName: string,
  ) => Promise<string>;
}

async function ingestSpecGlossGlb(page: import('@playwright/test').Page): Promise<void> {
  await page.evaluate(async () => {
    const w = window as unknown as BasherWindow;
    const bytes = new Uint8Array(
      await fetch('/assets/specgloss-quad.glb').then((r) => r.arrayBuffer()),
    );
    await w.__basher_ingestGltfFolder(
      [{ relativePath: 'specgloss-quad.glb', bytes }],
      'specgloss-glb',
    );
  });
}

/** Every captured material, keyed by material name, with the road each mesh took. */
const capturedMaterials = async (page: import('@playwright/test').Page) => {
  const out: Record<string, CapturedMaterial & { road: string }> = {};
  for (const mesh of await importedMeshes(page)) {
    for (const m of mesh.slots as (CapturedMaterial | null)[]) {
      if (m) out[m.name] = { ...m, road: mesh.road };
    }
  }
  return out;
};

const drawn = (page: import('@playwright/test').Page) => drawnImportMeshes(page);

test.describe('glTF spec/gloss .glb → metal-rough at ingest (#216)', () => {
  test('factor + diffuseTexture material converts; the draw is textured', async ({ page }) => {
    await page.goto('/');
    await page.waitForFunction(
      () => typeof (window as unknown as BasherWindow).__basher_ingestGltfFolder === 'function',
    );
    await ingestSpecGlossGlb(page);

    await expect
      .poll(async () => (await capturedMaterials(page))['SGDiffuse']?.name)
      .toBe('SGDiffuse');
    const diffuse = (await capturedMaterials(page))['SGDiffuse'];
    expect(diffuse.road).toBe('native');
    expect(diffuse.base.metalness).toBe(0); // specularFactor 0 → dielectric
    expect(diffuse.specular.roughness).toBeCloseTo(0.6, 5); // 1 - glossiness 0.4
    // diffuseTexture → baseColorTexture, stored in the project as sRGB.
    expect(diffuse.maps.albedo).toMatchObject({ store: 'project', colorSpace: 'srgb' });

    // side B — a drawn mesh carries a decoded base map.
    await expect
      .poll(async () => (await drawn(page)).some((m) => m.hasMap && m.mapImageOk))
      .toBe(true);
  });

  test('combined specularGlossinessTexture (a BIN bufferView image) bakes an MR map', async ({
    page,
  }) => {
    await page.goto('/');
    await page.waitForFunction(
      () => typeof (window as unknown as BasherWindow).__basher_ingestGltfFolder === 'function',
    );
    await ingestSpecGlossGlb(page);

    // side A — the combined material has BAKED roughness + metalness maps, both
    // linear, and the factors are 1× (the value lives in the texture).
    await expect
      .poll(async () => (await capturedMaterials(page))['SGCombined']?.maps?.metalness?.store)
      .toBe('project');
    const combined = (await capturedMaterials(page))['SGCombined'];
    expect(combined.road).toBe('native');
    expect(combined.maps.roughness).toMatchObject({ store: 'project', colorSpace: 'srgb-linear' });
    expect(combined.maps.metalness).toMatchObject({ store: 'project', colorSpace: 'srgb-linear' });
    // roughness + metalness share the ONE baked metallicRoughness image.
    expect(combined.maps.roughness?.hash).toBe(combined.maps.metalness?.hash);
    expect(combined.base.metalness).toBe(1); // metallicFactor 1 (texture carries the value)
    expect(combined.specular.roughness).toBe(1); // roughnessFactor 1

    // side B — the drawn material carries a metalness/roughness map (render == capture).
    await expect
      .poll(async () => (await drawn(page)).some((m) => m.hasMetalnessMap || m.hasRoughnessMap))
      .toBe(true);
  });

  test('a coloured-specular metal bakes a base-color map from the specular (#218)', async ({
    page,
  }) => {
    // The gold metal fixture: a solid-gold combined specularGlossinessTexture with
    // a black diffuse — the tint lives ONLY in the specular channel. The old path
    // kept the (black) diffuse as base color → the metal rendered near-black. #218
    // reconstructs the base color from the specular and bakes it as a baseColorTexture.
    await page.goto('/');
    await page.waitForFunction(
      () => typeof (window as unknown as BasherWindow).__basher_ingestGltfFolder === 'function',
    );
    await page.evaluate(async () => {
      const w = window as unknown as BasherWindow;
      const bytes = new Uint8Array(
        await fetch('/assets/specgloss-metal-quad.glb').then((r) => r.arrayBuffer()),
      );
      await w.__basher_ingestGltfFolder(
        [{ relativePath: 'specgloss-metal-quad.glb', bytes }],
        'specgloss-metal',
      );
    });

    // side A — the metal has a BAKED base-color (albedo) map (sRGB) — the fixture has
    // no diffuse texture, so an albedo map exists only because the specular was baked —
    // plus the metalness map. metallicFactor is 1 (the texture carries the value).
    await expect
      .poll(async () => (await capturedMaterials(page))['SGMetal']?.maps?.albedo?.store)
      .toBe('project');
    const metal = (await capturedMaterials(page))['SGMetal'];
    expect(metal.road).toBe('native');
    expect(metal.maps.albedo).toMatchObject({ store: 'project', colorSpace: 'srgb' });
    expect(metal.maps.metalness).toMatchObject({ store: 'project', colorSpace: 'srgb-linear' });
    expect(metal.maps.albedo?.hash).not.toBe(metal.maps.metalness?.hash);
    expect(metal.base.metalness).toBe(1);

    // side B — the drawn material carries BOTH a base map and a metalness map (the
    // metal renders with its gold tint).
    await expect.poll(async () => (await drawn(page)).some((m) => m.hasMap)).toBe(true);
    await expect.poll(async () => (await drawn(page)).some((m) => m.hasMetalnessMap)).toBe(true);
  });
});
