// glTF spec/gloss .glb direct-import (#216, V53) — the binary-container twin of
// gltf-specgloss-capture.spec.ts (#214, which covers the .gltf folder).
//
// A spec/gloss .glb used to import flat-gray: ingestGltfFolder gated the
// KHR_materials_pbrSpecularGlossiness → metal-rough conversion on the .gltf
// extension because Basher had no GLB writer. #216 adds repackGlb + convertSpecGlossGlb,
// so a .glb now converts AT INGEST exactly like a .gltf — one point before BOTH
// readers of the OPFS bytes (the render GLTFLoader clone AND the capture
// buildGltfImportOps), so render == capture.
//
// THE BOUNDARY-PAIR PROOF (falsifiable). The fixture (public/assets/specgloss-quad.glb,
// generated by scripts/gen-specgloss-glb-fixture.mjs) has TWO spec/gloss materials
// and stores its combined specularGlossinessTexture as a bufferView image INSIDE
// the embedded BIN chunk (the realistic GLB case the .gltf path's sibling resolver
// can't reach):
//   side A (the DAG IR) — each GltfChild's captured material is normal metal-rough
//     (roughness from glossiness, an albedo from diffuse, and — for the combined
//     material — a BAKED metallicRoughness map descriptor).
//   side B (the live clone) — the rendered three.js material carries the base map
//     and, for the combined material, a metalnessMap/roughnessMap.
// Pre-#216 both materials would be default-white with null maps (and the required
// extension would break the loader). The two sides agreeing = render == capture.

import { test, expect } from './_fixtures';

interface CapturedMap {
  hash: string;
  colorSpace: string;
  flipY: boolean;
  gltfTexture?: number;
}
interface CapturedMaterial {
  name: string;
  base: { color: string; metalness: number };
  specular: { roughness: number };
  maps: {
    albedo: CapturedMap | null;
    roughness: CapturedMap | null;
    metalness: CapturedMap | null;
  };
}
interface BasherWindow {
  __basher_dag: {
    getState: () => {
      state: {
        nodes: Record<string, { id: string; type: string; params: Record<string, unknown> }>;
      };
    };
  };
  __basher_ingestGltfFolder: (
    files: { relativePath: string; bytes: Uint8Array }[],
    folderName: string,
  ) => Promise<string>;
  __basher_gltf_meshes?: () => {
    name: string;
    hasMap: boolean;
    hasMetalnessMap: boolean;
    hasRoughnessMap: boolean;
  }[];
}

async function ingestSpecGlossGlb(page: import('@playwright/test').Page): Promise<void> {
  await page.evaluate(async () => {
    const w = window as unknown as BasherWindow;
    const bytes = new Uint8Array(
      await fetch('/assets/specgloss-quad.glb').then((r) => r.arrayBuffer()),
    );
    await w.__basher_ingestGltfFolder([{ relativePath: 'specgloss-quad.glb', bytes }], 'specgloss-glb');
  });
}

const capturedMaterials = (page: import('@playwright/test').Page) =>
  page.evaluate(() => {
    const w = window as unknown as BasherWindow;
    const nodes = Object.values(w.__basher_dag.getState().state.nodes);
    const out: Record<string, CapturedMaterial> = {};
    for (const n of nodes) {
      if (n.type !== 'GltfChild' || !Array.isArray(n.params.materials)) continue;
      for (const m of n.params.materials as CapturedMaterial[]) out[m.name] = m;
    }
    return out;
  });

const meshes = (page: import('@playwright/test').Page) =>
  page.evaluate(() => {
    const w = window as unknown as BasherWindow;
    return w.__basher_gltf_meshes ? w.__basher_gltf_meshes() : [];
  });

test.describe('glTF spec/gloss .glb → metal-rough at ingest (#216)', () => {
  test('factor + diffuseTexture material converts; clone renders textured', async ({ page }) => {
    await page.goto('/');
    await page.waitForFunction(
      () => typeof (window as unknown as BasherWindow).__basher_ingestGltfFolder === 'function',
    );
    await ingestSpecGlossGlb(page);

    await expect.poll(async () => (await capturedMaterials(page))['SGDiffuse']?.name).toBe(
      'SGDiffuse',
    );
    const diffuse = (await capturedMaterials(page))['SGDiffuse'];
    expect(diffuse.base.metalness).toBe(0); // specularFactor 0 → dielectric
    expect(diffuse.specular.roughness).toBeCloseTo(0.6, 5); // 1 - glossiness 0.4
    // diffuseTexture → baseColorTexture, captured as an sRGB imported descriptor.
    expect(diffuse.maps.albedo).toMatchObject({ hash: '', colorSpace: 'srgb', gltfTexture: 0 });

    // side B — a clone mesh still carries the base map (render byte-faithful).
    await expect.poll(async () => (await meshes(page)).some((m) => m.hasMap)).toBe(true);
  });

  test('combined specularGlossinessTexture (a BIN bufferView image) bakes an MR map', async ({
    page,
  }) => {
    await page.goto('/');
    await page.waitForFunction(
      () => typeof (window as unknown as BasherWindow).__basher_ingestGltfFolder === 'function',
    );
    await ingestSpecGlossGlb(page);

    // side A — the combined material has BAKED roughness + metalness map
    // descriptors (a new glTF texture, index ≥ 2, beyond the fixture's two),
    // both linear, and the factors are 1× (the value lives in the texture).
    await expect
      .poll(async () => (await capturedMaterials(page))['SGCombined']?.maps?.metalness?.gltfTexture)
      .toBeGreaterThanOrEqual(2);
    const combined = (await capturedMaterials(page))['SGCombined'];
    expect(combined.maps.roughness).toMatchObject({ hash: '', colorSpace: 'srgb-linear' });
    expect(combined.maps.metalness).toMatchObject({ hash: '', colorSpace: 'srgb-linear' });
    // roughness + metalness share the ONE baked metallicRoughness texture.
    expect(combined.maps.roughness?.gltfTexture).toBe(combined.maps.metalness?.gltfTexture);
    expect(combined.base.metalness).toBe(1); // metallicFactor 1 (texture carries the value)
    expect(combined.specular.roughness).toBe(1); // roughnessFactor 1

    // side B — the rendered clone carries a metalness/roughness map (the baked
    // data-URI image loaded; render == capture).
    await expect
      .poll(async () => (await meshes(page)).some((m) => m.hasMetalnessMap || m.hasRoughnessMap))
      .toBe(true);
  });

  test('a coloured-specular metal bakes a base-color map from the specular (#218)', async ({
    page,
  }) => {
    // The gold metal fixture: a solid-gold combined specularGlossinessTexture with
    // a black diffuse — the tint lives ONLY in the specular channel. The old path
    // kept the (black) diffuse as base color → the metal rendered near-black. #218
    // reconstructs the base color from the specular and bakes it as a baseColorTexture.
    await page.goto('/');
    await page.waitForFunction(
      () => typeof (window as unknown as BasherWindow).__basher_ingestGltfFolder === 'function',
    );
    await page.evaluate(async () => {
      const w = window as unknown as BasherWindow;
      const bytes = new Uint8Array(
        await fetch('/assets/specgloss-metal-quad.glb').then((r) => r.arrayBuffer()),
      );
      await w.__basher_ingestGltfFolder(
        [{ relativePath: 'specgloss-metal-quad.glb', bytes }],
        'specgloss-metal',
      );
    });

    // side A — the metal has a BAKED base-color (albedo) map descriptor (sRGB),
    // not the black diffuse it started with, plus the metalness map. metallicFactor
    // is 1 (the texture carries the value).
    await expect
      .poll(async () => (await capturedMaterials(page))['SGMetal']?.maps?.albedo?.gltfTexture)
      .toBeGreaterThanOrEqual(1);
    const metal = (await capturedMaterials(page))['SGMetal'];
    expect(metal.maps.albedo).toMatchObject({ hash: '', colorSpace: 'srgb' });
    expect(metal.maps.metalness).toMatchObject({ hash: '', colorSpace: 'srgb-linear' });
    expect(metal.base.metalness).toBe(1);

    // side B — the rendered clone carries BOTH a base map and a metalness map (the
    // baked base-color data-URI loaded; the metal renders with its gold tint).
    await expect.poll(async () => (await meshes(page)).some((m) => m.hasMap)).toBe(true);
    await expect
      .poll(async () => (await meshes(page)).some((m) => m.hasMetalnessMap))
      .toBe(true);
  });
});
