// Draco-compressed glTF loads end-to-end (#80 runtime proof).
//
// Pre-#80 this was impossible: drei's `useGLTF` defaulted to fetching
// the Draco decoder from `https://www.gstatic.com/draco/...` (drei
// `Gltf.js:8`), which in a self-hosted Playwright run typically fails
// (offline / CSP) and the suspense throw blanks the viewport. #80
// switches to a self-hosted `/draco/` decoder + adds KTX2 via
// `extendLoader`. This test loads a real Draco-encoded `.glb` fixture
// (`public/assets/cube-draco.glb`, generated by gltf-pipeline) through
// the standard `GltfAsset` node + scene wiring, then asserts the
// evaluated render-output has the asset as a renderable child — proof
// the decoder was registered and the asset deserialised.
//
// Boundary-pair (H40 detection question): we observe the PRODUCER side
// (the evaluator output via `__basher_evaluate`), not the rendered DOM.
// That's the appropriate side here — Draco decoding lives entirely on
// the producer/loader side of the SceneFromDAG boundary; the DOM
// surface is identical for any glTF.
//
// REF: #80, src/viewport/gltfLoaderConfig.ts,
// src/viewport/SceneFromDAG.tsx GltfAssetR, public/assets/cube-draco.glb.

import { test, expect } from './_fixtures';

interface BasherWindow {
  __basher_dag: {
    getState: () => {
      state: {
        nodes: Record<string, { type: string; params?: Record<string, unknown> }>;
        outputs: { render?: { node: string }; scene?: { node: string } };
      };
      dispatch: (op: unknown) => void;
      dispatchAtomic?: (ops: unknown[], source?: string, label?: string) => void;
    };
  };
  __basher_evaluate: (
    nodeId: string,
    ctx?: { time: { frame: number; seconds: number; normalized: number } },
  ) => { value: unknown };
}

test.beforeEach(async ({ page }) => {
  await page.goto('/');
  await page.evaluate(async () => {
    if (typeof navigator?.storage?.getDirectory === 'function') {
      const root = await navigator.storage.getDirectory();
      try {
        await root.removeEntry('basher', { recursive: true });
      } catch {
        /* OPFS entry absent on first run */
      }
    }
  });
  await page.reload();
  await expect(page.getByTestId('layout')).toBeVisible({ timeout: 10_000 });
  await page.waitForFunction(() => {
    const w = window as unknown as BasherWindow;
    return Boolean(w.__basher_dag && w.__basher_evaluate);
  });
});

test('P0 #80 — a Draco-compressed glTF loads through GltfAsset (self-hosted decoder)', async ({
  page,
}) => {
  // Strong-proof side-channel: if the Draco decoder is NOT registered
  // (or its WASM fetch fails — the pre-#80 CDN failure mode), three's
  // GLTFLoader logs an error to the console. Listen for any such error
  // throughout the test and fail loudly if one fires. This converts
  // the test from "wires-up-and-doesn't-crash" to "decoder actually
  // worked." (The DAG-eval assertions below remain — they prove the
  // scene-walk found the asset as a renderable child.)
  const loaderErrors: string[] = [];
  page.on('console', (msg) => {
    if (msg.type() !== 'error') return;
    const text = msg.text();
    if (/DRACOLoader|KHR_draco_mesh_compression|parse glTF|GLTFLoader|Failed to load/i.test(text)) {
      loaderErrors.push(text);
    }
  });

  // The fixture is the standard bundled cube re-encoded with Draco mesh
  // compression. Without the #80 fix the loader throws on the
  // KHR_draco_mesh_compression extension (no decoder registered, or
  // the decoder fetch from gstatic.com fails) and `gltf.scene` is
  // never resolved → the evaluator's value carries no renderable
  // primitive for the GltfAsset node. With the fix, the self-hosted
  // `/draco/` decoder deserialises the mesh and the GltfAsset evaluates
  // to a renderable.
  const renderable = await page.evaluate(async () => {
    const w = window as unknown as BasherWindow;
    const dag = w.__basher_dag!.getState();
    const sceneRef = dag.state.outputs.scene;
    if (!sceneRef) throw new Error('no scene output');

    const ops = [
      {
        type: 'addNode',
        nodeId: 'p80_g',
        nodeType: 'GltfAsset',
        params: { assetRef: 'assets/cube-draco.glb' },
      },
      {
        type: 'connect',
        from: { node: 'p80_g', socket: 'out' },
        to: { node: sceneRef.node, socket: 'children' },
      },
    ];
    if (dag.dispatchAtomic) {
      dag.dispatchAtomic(ops, 'user', 'p80 draco import');
    } else {
      ops.forEach((op) => dag.dispatch(op));
    }

    // Poll the evaluator for the GltfAsset's value. The loader is
    // suspense-driven so the first eval may return undefined while
    // useGLTF is still resolving the asset; we retry briefly to absorb
    // that. The PRODUCER-side proof: the node's evaluated `value` is a
    // GltfAsset spec with a non-empty `assetRef`. (The renderer side
    // resolving to a real THREE.Group is implicitly verified by the
    // scene-child eval below; the eval surfaces the value the loader
    // emits, which is the `kind: 'GltfAsset'` content key.)
    let value: unknown = null;
    for (let i = 0; i < 30; i++) {
      try {
        value = w.__basher_evaluate('p80_g', {
          time: { frame: 0, seconds: 0, normalized: 0 },
        }).value;
        if (value) break;
      } catch {
        /* keep polling */
      }
      await new Promise((r) => setTimeout(r, 100));
    }

    // Also evaluate the scene root and assert the GltfAsset child is
    // present in scene.children — the renderer's own walk.
    const sceneVal = w.__basher_evaluate(sceneRef.node, {
      time: { frame: 0, seconds: 0, normalized: 0 },
    }).value as { children?: Array<{ kind?: string; assetRef?: string }> };
    const child = sceneVal?.children?.find((c) => c?.kind === 'GltfAsset');

    return {
      nodeValue: value as { kind?: string; assetRef?: string } | null,
      childKind: child?.kind ?? null,
      childAssetRef: child?.assetRef ?? null,
    };
  });

  console.log(`[P0 #80] renderable=${JSON.stringify(renderable)}`);
  expect(renderable.nodeValue?.kind).toBe('GltfAsset');
  expect(renderable.nodeValue?.assetRef).toBe('assets/cube-draco.glb');
  expect(renderable.childKind).toBe('GltfAsset');
  expect(renderable.childAssetRef).toBe('assets/cube-draco.glb');

  // Final live observation: the loader's suspense actually resolves —
  // i.e. there's no perpetual fallback / no thrown error sticking. Wait
  // for the canvas to be present and the page not to be in an error
  // state. (No specific DOM assertion for the cube pixels — that's the
  // P3#7 PostFx pixel-diff territory; this test scopes to: did the
  // Draco decoder do its job?)
  const canvas = page.locator('canvas').first();
  await expect(canvas).toBeVisible({ timeout: 5_000 });

  // Give the suspense loader a moment to surface any deferred decoder
  // error (the load is async; the eval polling above gives ~3s headroom,
  // but a Draco WASM init failure can surface slightly later as the
  // wrapper script promise rejects). 500ms is enough in practice.
  await page.waitForTimeout(500);
  expect(
    loaderErrors,
    `Draco/GLTFLoader console.error fired — decoder is not wired correctly:\n${loaderErrors.join('\n')}`,
  ).toEqual([]);
});
