// A4 — text-to-3D. These tests pin the one claim the phase makes: a generated
// mesh takes the identical code path an imported GLB takes.
//
// The strongest of them is "the identical road": the Ops produced for generated
// bytes are deep-equal to the Ops `buildGltfImportOps` produces for those same
// bytes arriving as a file. Equality there is what makes a provenance branch
// unconstructible rather than merely absent today.
//
// The second strongest is the licence refusal, and it is worth reading twice: it
// asserts that NO REQUEST IS ISSUED, not merely that an error is thrown. For a
// paid service under unread terms, the call itself is the thing to prevent.

import { beforeEach, describe, expect, it, vi } from 'vitest';
import { __resetRegistryForTests, applyOp, emptyDagState } from '../dag';
import { registerAllNodes } from '../../nodes/registerAll';
import { buildGltfImportOps } from '../import/gltfImportChain';
import { parseGltfContainer } from '../import/glb';
import { ModelNotLicensedError, assertModelAllowed } from '../licensing/allowedModels';
import {
  MAX_FACE_LIMIT,
  ModelRequestInvalidError,
  StubModelGenerationCapability,
  TripoModelGenerationCapability,
  TRIPO_SERVICE_ID,
  assertValidModelRequest,
  synthesiseGlb,
  type ModelGenerationRequest,
} from './index';
import { MODEL_RECORDS } from '../licensing/allowedModels';
import type { DagState } from '../dag/state';

const KEY = 'tsk_test_key';
// Deliberately neutral. An earlier version used `.../generated/...` and the
// provenance scan below then matched the TEST'S OWN fixture path rather than
// anything the importer wrote — a fixture that defeats its own assertion. A user
// may name an imported folder anything, so the path must carry no word the scan
// is looking for.
const ASSET_REF = 'user-imports/chair/model.glb';

beforeEach(() => {
  __resetRegistryForTests();
  registerAllNodes();
});

function sceneState(): { state: DagState; sceneId: string } {
  let s = emptyDagState();
  s = applyOp(s, { type: 'addNode', nodeId: 'scene', nodeType: 'Scene', params: {} }).next;
  return { state: s, sceneId: 'scene' };
}

const TEXT: ModelGenerationRequest = { source: 'text', prompt: 'a red chair' };

describe('the stub is deterministic, and actually generates a mesh', () => {
  it('emits a GLB the real parser accepts, not a placeholder token', () => {
    // A stub returning a sentinel would let every test below pass while proving
    // nothing about whether generated bytes can travel the import road.
    const { json } = parseGltfContainer(synthesiseGlb(TEXT));
    expect(json.meshes?.length).toBe(1);
    expect(json.accessors?.length).toBe(2);
    expect(json.bufferViews?.length).toBe(2);
  });

  it('returns identical bytes for an identical request', () => {
    const a = new Uint8Array(synthesiseGlb(TEXT));
    const b = new Uint8Array(synthesiseGlb(TEXT));
    expect(Array.from(a)).toEqual(Array.from(b));
  });

  it('returns a different mesh for a different prompt', () => {
    const a = new Uint8Array(synthesiseGlb(TEXT));
    const b = new Uint8Array(synthesiseGlb({ source: 'text', prompt: 'a blue table' }));
    expect(Array.from(a)).not.toEqual(Array.from(b));
  });

  it('the capability returns exactly what synthesiseGlb builds', async () => {
    // The stub's own claim, checked rather than assumed.
    const cap = new StubModelGenerationCapability();
    const result = await cap.generate(TEXT);
    expect(Array.from(new Uint8Array(result.glb))).toEqual(
      Array.from(new Uint8Array(synthesiseGlb(TEXT))),
    );
  });

  it('reports progress at both edges so a consumer is exercised offline', async () => {
    const seen: number[] = [];
    await new StubModelGenerationCapability().generate(TEXT, (p) => seen.push(p.progress));
    expect(seen).toEqual([0, 100]);
  });
});

describe('the generated bytes travel the import road, and carry nothing of their own', () => {
  // 🔴 The phase's FULL discriminating observation — generated-path ops equal
  // file-path ops — cannot be written here, and saying so is better than a test
  // that looks like it. Both roads must exist to compare, and the generated road
  // is the app/agent surface, not this module. An earlier draft compared
  // `buildGltfImportOps(capabilityBytes)` with `buildGltfImportOps(sameBytes)`:
  // both sides called one function with one input, so it held for every possible
  // implementation, including a wrong one. It proved only what the "returns
  // exactly what synthesiseGlb builds" test above already proves.
  //
  // What IS provable here is the half that belongs here: the bytes are accepted
  // by the real importer, and what comes out is indistinguishable in kind from an
  // import. The comparison of the two roads lands with the two roads.

  it('yields no node type an imported GLB does not also yield', async () => {
    const { state, sceneId } = sceneState();
    const { glb } = await new StubModelGenerationCapability().generate(TEXT);
    const { ops } = await buildGltfImportOps(
      { buffer: glb, assetRef: ASSET_REF, sceneNodeId: sceneId },
      state,
    );
    const nodeTypes = [
      ...new Set(
        ops
          .filter((o): o is Extract<typeof o, { type: 'addNode' }> => o.type === 'addNode')
          .map((o) => o.nodeType),
      ),
    ].sort();
    expect(nodeTypes).toEqual(['GltfAsset', 'GltfChild', 'Group']);
    // Nothing records provenance in the graph, because nothing may branch on it.
    expect(JSON.stringify(ops)).not.toMatch(/generated|provenance|tripo|stub/i);
  });

  it('the generated asset declares no feature the importer cannot carry', async () => {
    const { state, sceneId } = sceneState();
    const { glb } = await new StubModelGenerationCapability().generate(TEXT);
    const result = await buildGltfImportOps(
      { buffer: glb, assetRef: ASSET_REF, sceneNodeId: sceneId },
      state,
    );
    expect(result.unsupportedFeatures).toEqual([]);
  });

  it('this module builds no Ops of its own — the road is elsewhere, by construction', async () => {
    // The structural half of "no new downstream surface". If modelgen ever grows
    // its own op builder, that builder IS the second import road A4 exists to
    // avoid, and this reds the moment it appears.
    const mod = await import('./index');
    const suspicious = Object.keys(mod).filter((k) => /^build|Ops$|Chain$/.test(k));
    expect(suspicious).toEqual([]);
  });
});

describe('the request contract refuses rather than clamps', () => {
  it('rejects an empty prompt, naming the field', () => {
    try {
      assertValidModelRequest({ source: 'text', prompt: '  ' });
      throw new Error('expected a refusal');
    } catch (err) {
      expect(err).toBeInstanceOf(ModelRequestInvalidError);
      expect((err as ModelRequestInvalidError).issues.join()).toMatch(/prompt/);
    }
  });

  it('rejects a runaway face limit rather than silently capping it', () => {
    expect(() =>
      assertValidModelRequest({ source: 'text', prompt: 'x', faceLimit: MAX_FACE_LIMIT + 1 }),
    ).toThrow(ModelRequestInvalidError);
  });

  it('rejects a non-integer or negative face limit', () => {
    expect(() => assertValidModelRequest({ source: 'text', prompt: 'x', faceLimit: -5 })).toThrow(
      ModelRequestInvalidError,
    );
  });

  it('rejects an empty source image', () => {
    expect(() =>
      assertValidModelRequest({
        source: 'image',
        image: { bytes: new Uint8Array(0), mimeType: 'image/png' },
      }),
    ).toThrow(ModelRequestInvalidError);
  });

  it('the stub validates too — a degenerate request cannot be proven to "work"', async () => {
    await expect(
      new StubModelGenerationCapability().generate({ source: 'text', prompt: '' }),
    ).rejects.toThrow(ModelRequestInvalidError);
  });

  it.each([
    ['an empty prompt', { source: 'text', prompt: '' }],
    ['a runaway face limit', { source: 'text', prompt: 'x', faceLimit: MAX_FACE_LIMIT + 1 }],
    [
      'an empty source image',
      { source: 'image', image: { bytes: new Uint8Array(0), mimeType: 'image/png' } },
    ],
  ])(
    'the narrow road refuses %s exactly as the wide one does, so it is not a way around the gate',
    async (_label, bad) => {
      // `generateTaskOnly` skips `synthesiseGlb`, which is where the stub's wide
      // road happens to re-validate (#833). That is only safe if the validation
      // it skips is a DUPLICATE rather than a unique check — which is what this
      // asserts, by feeding the same bad requests to both and requiring the same
      // refusal from each.
      const cap = new StubModelGenerationCapability();
      await expect(cap.generate(bad as never)).rejects.toThrow(ModelRequestInvalidError);
      await expect(cap.generateTaskOnly(bad as never)).rejects.toThrow(ModelRequestInvalidError);
    },
  );
});

describe('the service licence gate, now that the Tripo verdict is recorded', () => {
  // This block used to assert the OPPOSITE — that the service had no verdict and
  // every generation refused. That was correct while the terms were unread, and
  // the premise test was written to red "the day someone records the terms, which
  // is exactly when the refusal below must be revisited rather than left to look
  // like a bug". It redded. This is that revisit.
  //
  // What must NOT be lost in the rewrite is the property that actually had teeth:
  // an unrecorded service still refuses, and refuses before any call. Deleting
  // these tests along with their premise would have quietly retired the gate.

  it('the Tripo service has a verdict, and the record says what it rests on', () => {
    const record = MODEL_RECORDS.find((r) => r.id === TRIPO_SERVICE_ID);
    expect(record).toBeDefined();
    expect(record!.verdict).toBe('ALLOWED');
    // The honesty of the record is itself worth pinning. Every other verdict here
    // meets a cited-text standard; this one rests on the product owner's decision,
    // and the reason field has to keep saying so — otherwise a later reader takes
    // it for a reading of the terms, which nobody has done.
    expect(record!.reason).toMatch(/OWNER'S DECISION, NOT A READING OF THE TERMS/i);
  });

  it('the gate still has teeth — an UNRECORDED service is refused, by name', () => {
    // The load-bearing half, retargeted. Recording one verdict must not turn the
    // gate off; it must only answer differently for the id that was recorded.
    expect(() => assertModelAllowed('some-service-nobody-recorded')).toThrow(ModelNotLicensedError);
    expect(() => assertModelAllowed('some-service-nobody-recorded')).toThrow(
      /no recorded licence verdict/,
    );
  });

  it('with the verdict recorded, a generation now REACHES the network', async () => {
    // The other side of the same coin, and the reason this is a test rather than
    // a comment: it proves the gate was ENABLED rather than removed. Before the
    // record, `fetchImpl` was never called; now it is, and by the licence gate's
    // leave rather than around it.
    const fetchImpl = vi.fn(
      async () => new Response(JSON.stringify({ data: { task_id: 't1' } }), { status: 200 }),
    );
    const cap = new TripoModelGenerationCapability({
      apiKey: KEY,
      timeoutMs: 20,
      pollIntervalMs: 0,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });
    // It will fail later, on the poll — what is under test is that it got past
    // the gate and issued the create call at all.
    await expect(cap.generate(TEXT)).rejects.toThrow();
    expect(fetchImpl).toHaveBeenCalled();
  });

  it('the stub is NOT gated — it reaches no service, so no terms govern it', async () => {
    // The asymmetry is deliberate and is the difference from A1, where the
    // licence unit was the checkpoint the stub stood in for.
    await expect(new StubModelGenerationCapability().generate(TEXT)).resolves.toBeTruthy();
  });
});
