// StubModelGenerationCapability — deterministic, offline, and it really does
// build a mesh.
//
// The stub emits a spec-valid GLB through `repackGlb`, the same writer the
// spec/gloss ingest uses, so what comes out is parsed by the same `parseGlb` an
// imported file goes through. A stub returning a sentinel string would let every
// test below it pass while proving nothing about whether generated bytes can
// travel the import road — which is the only claim phase A4 makes.
//
// It reaches NO service, so it does not consult the service licence verdict:
// nothing it produces is governed by anyone's terms. It DOES validate the
// request, because a stub that skipped validation would let a test prove a
// degenerate request works.
//
// Determinism (V2 — no Math.random, no Date.now): every number is derived by
// fnv1a-32 over a canonical serialisation of the request. Same request, same
// bytes; different prompt, different mesh.
//
// REF: ref/architecture/ai-track.md phase A4;
//      src/core/motiongen/StubMotionGenerationCapability.ts (the sibling);
//      src/core/import/glb.ts (`repackGlb`, the writer this leans on).

import { repackGlb } from '../import/glb';
import {
  assertValidModelRequest,
  describeRequest,
  type ModelGenerationCapability,
  type ModelGenerationProgress,
  type ModelTaskResult,
  type ModelGenerationRequest,
  type ModelGenerationResult,
} from './ModelGenerationCapability';

/** Default the stub reports when the caller named no version. Matches the SDK's
 *  own default so a switch to Http does not silently change what is recorded.
 *  REF: ref/sources/tripo-python-sdk/tripo3d/client.py:557 (`model_version`). */
export const DEFAULT_MODEL_VERSION = 'v2.5-20250123';

/** fnv1a-32 — small, dependency-free, deterministic. Same function the glTF
 *  import chain uses for content-addressed ids, for the same reason. */
function fnv1a32(input: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    h ^= input.charCodeAt(i);
    h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
  }
  return h >>> 0;
}

/** Canonical text for a request. Image bytes are folded in by length and by a
 *  rolling hash rather than by content, so two different images give two
 *  different meshes without holding either in memory twice. */
function canonicalise(request: ModelGenerationRequest): string {
  const parts: string[] = [request.source];
  if (request.source === 'text') {
    parts.push(request.prompt, request.negativePrompt ?? '', JSON.stringify(request.pose ?? {}));
  } else if (request.source === 'image') {
    parts.push(request.image.mimeType, String(request.image.bytes.byteLength));
    parts.push(String(fnv1a32(Array.from(request.image.bytes.slice(0, 256)).join(','))));
  } else {
    for (const [name, img] of Object.entries(request.views)) {
      if (!img) continue;
      parts.push(name, String(img.bytes.byteLength));
    }
  }
  parts.push(
    request.modelVersion ?? DEFAULT_MODEL_VERSION,
    String(request.modelSeed ?? ''),
    String(request.faceLimit ?? ''),
    String(request.quad ?? ''),
  );
  // U+0000 written as an ESCAPE, never as a literal byte. A NUL is the right
  // delimiter here - no prompt, mime type or version string can contain one, so
  // the join is unambiguous and two different requests cannot canonicalise the
  // same way. But a literal NUL in source makes grep classify the whole file as
  // binary and skip it SILENTLY, so every repo-wide sweep stops seeing this file
  // while git grep still does. The repo has a gate for exactly that, and it
  // caught this one.
  return parts.join('\u0000');
}

/**
 * A box whose proportions come from the request hash. Small enough to read in a
 * test, real enough that `parseGlb` → `buildGltfImportOps` treats it exactly as
 * it treats a file off disk.
 *
 * Exported so a test can assert the bytes the capability returns are the bytes
 * this builds — the stub's own claim, checked rather than assumed.
 */
export function synthesiseGlb(request: ModelGenerationRequest): ArrayBuffer {
  assertValidModelRequest(request);
  const h = fnv1a32(canonicalise(request));

  // Three independent dimensions in [0.5, 1.5), from disjoint bit ranges so a
  // one-character prompt change moves all three rather than only the low byte.
  const dim = (shift: number): number => 0.5 + (((h >>> shift) & 0xff) / 0xff) * 1.0;
  const [sx, sy, sz] = [dim(0), dim(8), dim(16)];

  const corners: [number, number, number][] = [
    [-sx, -sy, -sz],
    [sx, -sy, -sz],
    [sx, sy, -sz],
    [-sx, sy, -sz],
    [-sx, -sy, sz],
    [sx, -sy, sz],
    [sx, sy, sz],
    [-sx, sy, sz],
  ];
  // 12 triangles, CCW when viewed from outside.
  const tris = [
    0, 2, 1, 0, 3, 2, 4, 5, 6, 4, 6, 7, 0, 1, 5, 0, 5, 4, 3, 7, 6, 3, 6, 2, 1, 2, 6, 1, 6, 5, 0, 4,
    7, 0, 7, 3,
  ];

  const positions = new Float32Array(corners.flat());
  const indices = new Uint16Array(tris);

  // glTF 2.0 §3.6.2.4: a bufferView's byteOffset must be a multiple of the
  // component size. Positions are float32 (4) and land at 0; indices are uint16
  // (2) and land after the positions, whose length is already a multiple of 4.
  const posBytes = new Uint8Array(positions.buffer, 0, positions.byteLength);
  const idxBytes = new Uint8Array(indices.buffer, 0, indices.byteLength);
  // Pad the whole buffer to 4 so the GLB BIN chunk is aligned.
  const total = align4(posBytes.byteLength + idxBytes.byteLength);
  const bin = new Uint8Array(total);
  bin.set(posBytes, 0);
  bin.set(idxBytes, posBytes.byteLength);

  const json = {
    asset: { version: '2.0', generator: 'basher-stub-modelgen' },
    scene: 0,
    scenes: [{ nodes: [0] }],
    // The node name becomes the imported child's key, so give it something a
    // human reading the outliner can recognise.
    nodes: [{ mesh: 0, name: sanitiseNodeName(describeRequest(request)) }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1 }] }],
    accessors: [
      {
        bufferView: 0,
        componentType: 5126, // FLOAT
        count: corners.length,
        type: 'VEC3',
        min: [-sx, -sy, -sz],
        max: [sx, sy, sz],
      },
      {
        bufferView: 1,
        componentType: 5123, // UNSIGNED_SHORT
        count: indices.length,
        type: 'SCALAR',
      },
    ],
    bufferViews: [
      { buffer: 0, byteOffset: 0, byteLength: posBytes.byteLength },
      { buffer: 0, byteOffset: posBytes.byteLength, byteLength: idxBytes.byteLength },
    ],
    buffers: [{ byteLength: total }],
  };

  const bytes = repackGlb({ json, bin });
  // Detach a plain, non-shared ArrayBuffer — the same concern importGltf handles
  // at its own seam, for the same reason (Uint8Array.buffer is ArrayBufferLike).
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  return copy.buffer;
}

function align4(n: number): number {
  return (n + 3) & ~3;
}

/** glTF node names reach THREE's PropertyBinding, which fails silently on the
 *  reserved set. Same class the BVH importer sanitises for. */
function sanitiseNodeName(name: string): string {
  const cleaned = name.replace(/[[\].:/]/g, '_').trim();
  return cleaned.length > 0 ? cleaned : 'generated';
}

export class StubModelGenerationCapability implements ModelGenerationCapability {
  readonly id = 'stub-modelgen';
  readonly kind = 'stub' as const;

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async generate(
    request: ModelGenerationRequest,
    onProgress?: (p: ModelGenerationProgress) => void,
  ): Promise<ModelGenerationResult> {
    // Redundant with `synthesiseGlb`, which validates as its own first act, and
    // kept on purpose: this is the entry a caller sees, so a refusal should come
    // from here rather than from two frames down. Measured — removing THIS line
    // alone changes no test, because synthesiseGlb still refuses; removing both
    // reds the contract test. Do not delete it as a duplicate without moving the
    // enforcement, or the error's origin moves with it.
    assertValidModelRequest(request);
    const taskId = `stub_${fnv1a32(canonicalise(request)).toString(16)}`;
    // Report the same two edges a real task reports, so a progress consumer is
    // exercised offline rather than only against the service.
    onProgress?.({ taskId, status: 'running', progress: 0 });
    const glb = synthesiseGlb(request);
    onProgress?.({ taskId, status: 'success', progress: 100 });
    return { taskId, glb, modelVersion: request.modelVersion ?? DEFAULT_MODEL_VERSION };
  }

  /**
   * The same task without its output, mirroring the service's contract.
   *
   * 🔑 IT DOES NOT SYNTHESISE THE MESH, AND THAT IS THE POINT. Delegating to
   * `generate` and narrowing the result would make the stub produce bytes no
   * caller asked for — the exact shape of the defect this method exists to
   * remove (#833) — and, worse, it would make the app-level gate unable to see
   * the difference: a spy on `generate` would fire either way, so a regression
   * to the wide call would stay green.
   *
   * The refusals stay identical because `assertValidModelRequest` is what both
   * roads validate with. `synthesiseGlb` re-validates as its own first act, so
   * skipping it skips a duplicate check, not a unique one — pinned by a test
   * that feeds the same bad requests to both.
   */
  async generateTaskOnly(
    request: ModelGenerationRequest,
    onProgress?: (p: ModelGenerationProgress) => void,
  ): Promise<ModelTaskResult> {
    assertValidModelRequest(request);
    const taskId = `stub_${fnv1a32(canonicalise(request)).toString(16)}`;
    onProgress?.({ taskId, status: 'running', progress: 0 });
    onProgress?.({ taskId, status: 'success', progress: 100 });
    return { taskId, modelVersion: request.modelVersion ?? DEFAULT_MODEL_VERSION };
  }

  async cancel(): Promise<void> {
    // Nothing to cancel — generation is synchronous here.
  }
}
